### PR TITLE
Fix build on kernel 6.8+

### PR DESCRIPTION
**Pull request by sakarie9**
Fix an error caused by `strlcpy` on Linux kernel 6.8+ which causes the following issue

```
/var/lib/dkms/vendor-reset/r114.4b466e9/build/src/amd/amdgpu/atom.c:1427:3: error: call to undeclared library function 'strlcpy' with type 'unsigned long (char *, const char *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
```

Similar bugs and fixes form [v4l2loopback-dkms FTBS in noble with the latest linux 6.8 kernel ](https://bugs.launchpad.net/ubuntu/+source/v4l2loopback/+bug/2052801)

### CODE REVIEW

**Comment by Keridos** [comment]
Please merge this
