### ISSUE TITLE
Does not compile on kernel 6.12 (missing file asm/unaligned.h)

### ISSUE THREAD

**Issue by fseoane** [gnif/vendor-reset#87]
Hi.

It does not build in kernel 6.12 giving an error of a missing file asm/unaligned.h (looks this file is not included in linux-headers for this kernel version)

System: 
- Arch linux 
- Kernel 6.12.1-arch1-1

Log file attached. 
[make.log](https://github.com/user-attachments/files/17894572/make.log)
Error at lines 56 to 59:
`/var/lib/dkms/vendor-reset/r117.084881c/build/src/amd/amdgpu/atom.c:32:10: fatal error: asm/unaligned.h: No such file or directory
   32 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.`

**Comment by fseoane** [comment]
Found the solution in the pull request:  **Fix build on Kernel v. 6.12 #86** 
To fix it, a change in line 32 at file `src/amd/amdgpu/atom.c` must be done to import `unaligned.h` from `linux` instead from `asm`, changing that line 32 from 
`#include <asm/unaligned.h>`
to 
`#include <linux/unaligned.h>`

**Comment by Sideflare** [comment]
In addition to this awesome suggestion by @fseoane I had to do a little bit of additional configurising in order to complete the installation. Here's all my notes in the hope that it helps someone else.  

cMP51 PVE 9.0.11 Dual Vega 56/64 Pixlas and Backplane

GPU PASSTHROUGH SYSTEM CONFIGURATION

ADD VFIO CONFIG - cat /etc/modules-load.d/vfio.conf

```
vfio
vfio_iommu_type1
vfio_pci

```
—————————

ADD TO GRUB - cat /etc/default/grub 

```
GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt pcie_acs_override=downstream"
```
UPDATE GRUB AND INITRAMFS

```
update-grub && update-initramfs -u -k all
```
GPU PASSTHROUGH TROUBLESHOOTING SCRIPT - information only does not modify your system
```
#!/bin/bash
# ======================================================================
# GPU Passthrough & Vendor Reset Diagnostic Script
# Evaluates system configuration, IOMMU groups, VFIO binding, ROM, and VM configs
# Safe: does not modify anything
# Designed for Proxmox VE 9+, GNIF vendor-reset, and AMD/other GPUs
# ======================================================================

echo "=== GPU Passthrough Diagnostic ==="
echo "Node: $(hostname)"
echo "Date: $(date)"
echo

# ----------------------------
# 1. Check for required modules
# ----------------------------
echo "Loaded VFIO / vendor-reset modules:"
lsmod | egrep 'vfio|vendor_reset' || echo "⚠ WARNING: VFIO/vendor-reset modules not loaded"
echo

# ----------------------------
# 2. Kernel command line
# ----------------------------
echo "Kernel command line:"
cat /proc/cmdline
echo

# ----------------------------
# 3. IOMMU groups and device bindings
# ----------------------------
echo "IOMMU Groups and PCI devices:"
for grp in /sys/kernel/iommu_groups/*; do
    echo "Group $(basename $grp):"
    for dev_path in "$grp"/devices/*; do
        dev=$(basename "$dev_path")
        desc=$(lspci -nnk -s "$dev" 2>/dev/null)
        drv=$(lspci -nnk -s "$dev" 2>/dev/null | grep "Kernel driver in use" | cut -d':' -f2-)
        echo "  Device $dev: $desc"
        if [[ -z "$drv" ]]; then
            echo "    ⚠ Not bound to any driver"
        else
            echo "    ✅ Driver in use: $drv"
        fi
    done
done
echo

# ----------------------------
# 4. ROM file check (if AMD GPU)
# ----------------------------
ROMFILE="/usr/share/kvm/snippets/AMD.RXVega64.8176.170811.rom"
if [[ -f "$ROMFILE" ]]; then
    echo "ROM file exists: $ROMFILE"
else
    echo "⚠ ROM file missing: $ROMFILE"
fi
echo

# ----------------------------
# 5. VM configs checking for passthrough and reset-method
# ----------------------------
echo "Checking VM configs for GPU passthrough and reset-method:"
for vmconf in /etc/pve/qemu-server/*.conf; do
    echo "VM Config: $(basename "$vmconf")"
    grep -E 'hostpci|bios|machine|args|cpu' "$vmconf"
    if grep -q "reset-method" "$vmconf"; then
        echo "  ⚠ reset-method present (may need update for Proxmox 9+)"
    else
        echo "  ✅ No reset-method conflicts detected"
    fi
done
echo

# ----------------------------
# 6. IOMMU / DMAR in dmesg
# ----------------------------
echo "IOMMU / DMAR messages from dmesg (first 20 lines):"
dmesg | grep -i -e iommu -e DMAR | head -n 20 || echo "No IOMMU/DMAR messages found"
echo

# ----------------------------
# 7. Hugepages config
# ----------------------------
echo "Hugepages configuration:"
grep -i huge /etc/sysctl.conf /etc/pve/* 2>/dev/null || echo "No hugepages config found"
grep -i huge /proc/meminfo | grep -v 0 || echo "No hugepages allocated"
echo

# ----------------------------
# 8. PCI devices overview
# ----------------------------
echo "PCI devices on node:"
pvesh get /nodes/$(hostname)/hardware/pci --pci-class-blacklist "" || echo "Failed to query PCI devices"
echo

echo "=== GPU Passthrough Diagnostic Complete ==="
```




# gnif/VENDOR RESET INSTALLATION
#Clone the repo to a temporary location
```
cd /tmp
git clone https://github.com/gnif/vendor-reset.git vendor-reset-1.0
```
#Copy the repo to /usr/src for DKMS
```
sudo cp -r /tmp/vendor-reset-1.0 /usr/src/
```

#Edit atom.c - find “<asm/unaligned.h>” replace with <linux/unaligned.h> (will fail without this mod)
```
sudo nano /usr/src/vendor-reset-1.0/src/amd/amdgpu/atom.c
```

```
#Remove any old DKMS module (if installed)
sudo dkms remove -m vendor-reset -v 1.0 --all
#Add the module to DKMS
sudo dkms add -m vendor-reset -v 1.0
#Build the module (force was required)
sudo dkms build -m vendor-reset -v 1.0 --force
#check for errors
cat /tmp/vendor-reset-build.log
```

#Install the module
```
sudo dkms install -m vendor-reset -v 1.0
```

#Load the module immediately (without reboot)
```
sudo modprobe vendor-reset
```

#Verify
```
dkms status && lsmod | grep vendor-reset
```

#Load the module automatically at boot
```
echo "vendor-reset" | sudo tee /etc/modules-load.d/vendor-reset.conf
```



...AND it still doesnt work....   but at least i got vendor-reset installed 🤣🤣🤣
